###################### Vortex Configuration Template ######################
#
# This template includes reinforcement learning enabled by default for all modes
#
##############################################################################

#################################### Core ####################################
# General core configurations
##############################################################################
[core]
# Base path for the workspace
workspace_base = "./workspace"

# Cache directory path
cache_dir = "/tmp/cache"

# Debugging enabled
debug = false

# Runtime environment
runtime = "local"

# Name of the default agent
default_agent = "VortexAgent"

# Maximum iterations
max_iterations = 500

# Path to store trajectories
save_trajectory_path = "./trajectories"

# Whether to save screenshots in the trajectory
save_screenshots_in_trajectory = true

#################################### LLM #####################################
# Configuration for LLM models
##############################################################################
[llm]
# Provider to use (openai, anthropic, ollama, etc.)
provider = "openai"

# API key to use (set this in your environment or .env file)
api_key = ""

# Model to use
model = "gpt-4o"

# Temperature for the API
temperature = 0.7

# Maximum number of output tokens
max_output_tokens = 1024

#################################### Agent ###################################
# Configuration for agents
##############################################################################
[agent]
# Whether the browsing tool is enabled
enable_browsing = true

# Whether the IPython tool is enabled
enable_jupyter = true

# Whether the LLM editor is enabled
enable_llm_editor = true

# Whether prompt extensions are enabled
enable_prompt_extensions = true

# Whether history truncation is enabled
enable_history_truncation = true

# LLM config group to use
llm_config = "llm"

#################################### Server ##################################
# Configuration for the web server
##############################################################################
[server]
# Host to bind the server to
host = "0.0.0.0"

# Port to run the server on
port = 12000

# Whether to run in debug mode
debug = false

# Log level
log_level = "info"

#################################### Security ###############################
# Security settings
##############################################################################
[security]
# Enable admin mode for unrestricted capabilities
admin_mode = true

# Disable confirmation mode to avoid prompts
confirmation_mode = false

# Disable security analyzer
enable_security_analyzer = false

#################################### Sandbox ###############################
# Sandbox environment settings
##############################################################################
[sandbox]
# Sandbox timeout in seconds
timeout = 300

# Use host network for unrestricted network access
use_host_network = true

# Enable GPU support if available
enable_gpu = true

# Keep runtime alive after session ends
keep_runtime_alive = true

#################################### RL ######################################
# Configuration for Reinforcement Learning (enabled by default)
##############################################################################
[rl]
# Whether to enable reinforcement learning
enabled = true

# Maximum number of turns in a conversation
max_turns = 10

# Maximum length of prompt
max_prompt_length = 2048

# Maximum length of response
max_response_length = 512

# Maximum length of observation
max_obs_length = 1024

# Whether to use ReAct format
react_format = true

# Strategy to use for rollout (StandardReAct/ToT/MCTS)
rollout_strategy = "StandardReAct"

# Backend for storing trajectories (mongodb/file)
storage_backend = "file"

# Maximum number of worker threads
max_workers = 10

# Path to store trajectories
trajectory_path = "./rl_trajectories"

# Whether to enable training
enable_training = true

# Learning rate for training
learning_rate = 1e-5

# Number of training epochs
num_epochs = 3

# Batch size for training
batch_size = 8

# Maximum gradient norm for clipping
max_grad_norm = 1.0

#################################### Learning ###############################
# Configuration for learning capabilities
##############################################################################
[learning]
# Whether learning is enabled
enabled = true

# Whether reinforcement learning is enabled
reinforcement_learning = true

# Whether knowledge acquisition is enabled
knowledge_acquisition = true

# Whether to automatically learn from user feedback
learn_from_feedback = true

# Whether to automatically learn from errors
learn_from_errors = true

# Path to store learned knowledge
knowledge_path = "./knowledge"

# Maximum size of knowledge base (in MB)
max_knowledge_size = 1000

# Frequency of knowledge consolidation (in hours)
consolidation_frequency = 24

#################################### Condenser #################################
# Condensers control how conversation history is managed and compressed when
# the context grows too large. Each agent uses one condenser configuration.
##############################################################################
[condenser]
# The type of condenser to use
type = "amortized"

# Number of initial events to always keep (typically includes task description)
keep_first = 1

# Maximum size of history before triggering forgetting
max_size = 100